-- SELECT *
-- FROM SH.CUSTOMERS
-- WHERE SUBSTR(CUST_FIRST_NAME, 1, 1) = SUBSTR(CUST_LAST_NAME, 1, 1);

-- SELECT CUST_LAST_NAME || ', ' || CUST_FIRST_NAME AS FULL_NAME
-- FROM SH.CUSTOMERS;

-- SELECT *
-- FROM SH.CUSTOMERS
-- WHERE CUST_LAST_NAME LIKE '%SON';

-- SELECT CUST_FIRST_NAME || ' ' || CUST_LAST_NAME AS FULL_NAME,
--        LENGTH(CUST_FIRST_NAME || ' ' || CUST_LAST_NAME) AS NAME_LENGTH
-- FROM SH.CUSTOMERS;

-- SELECT REGEXP_REPLACE(CUST_FIRST_NAME || ' ' || CUST_LAST_NAME, '[AEIOUaeiou]', '*') AS MASKED_NAME
-- FROM SH.CUSTOMERS;

-- SELECT *
-- FROM SH.CUSTOMERS
-- WHERE CUST_INCOME_LEVEL LIKE '%90%';

-- SELECT SUBSTR(CUST_FIRST_NAME, 1, 1) || SUBSTR(CUST_LAST_NAME, 1, 1) AS INITIALS
-- FROM SH.CUSTOMERS;

-- SELECT CUST_CITY || ', ' || CUST_STATE_PROVINCE AS FULL_ADDRESS
-- FROM SH.CUSTOMERS;

-- SELECT REGEXP_SUBSTR(CUST_INCOME_LEVEL, '\d+') AS INCOME_NUMERIC
-- FROM SH.CUSTOMERS;

-- SELECT COUNT(*) AS THREE_LETTER_FIRSTNAME_COUNT
-- FROM SH.CUSTOMERS
-- WHERE LENGTH(CUST_FIRST_NAME) = 3;

